### ISSUE TITLE
WeWork The Most Overvalued Company in the World?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/product-roadmap#10]
[![image](https://user-images.githubusercontent.com/194400/52160388-b4240280-26ac-11e9-92af-7d2a06063f5f.png)](https://youtu.be/DwAyUV6hTf8)
https://youtu.be/DwAyUV6hTf8
@iteles it's worth watching this video to _understand_ ***why*** there is "buzz" about "We" ... 📺

**Comment by nelsonic** [comment]
Not strictly relevant to our "Product Roadmap" so closing.

Further reading for anyone interested:

+ IPO https://news.ycombinator.com/item?id=19781549 
+ Financial Reality: https://news.ycombinator.com/item?id=18855680 (_insightful comments on how the "coworking" in WeWork is only "co" in name_...) The post describes how: 
> “_Going forward, the company will no longer be called WeWork but rather The We Company_.”  
And: “_Rather than just renting desks, the company aims to encompass all aspects of people’s lives, in both physical and digital worlds_” ...  🙄

**Comment by nelsonic** [comment]
+ https://www.profgalloway.com/wewtf-part-deux
+ https://www.theverge.com/2019/9/24/20882491/wework-adam-neumann-softbank-ceo
_discussing firing 40 percent of the workforce;  5,000 employees_
+ https://www.theverge.com/2019/11/6/20951946/softbank-masayoshi-son-admits-wework-was-bad-judgement-q2-2019
"_My judgement in investment was not right in many ways_,” Son said
_Despite owning 80 percent of the company, SoftBank doesn’t have full control of WeWork._ ... 🙄

**Comment by iteles** [comment]
Super interesting!

**Comment by nelsonic** [comment]
Yeah, it’s mind blowing that Neumann gets to _keep_ all the money he swindled from investors. I don’t know who is to “blame” ... I feel it’s the “entrepreneur” who oversold the value of the company and tried to convince people it is/was a “tech” company. But Masayoshi Son is not _stupid_, he’s just overly-optimistic. Prof Galloway suggests that Son (_and all the investment bankers_) _knew_ very well that it was over-valued and were just hoping to dump the stock on “retail” investors. 🙃

~~If~~ _when_ WeWork implodes I bet IWG (Regus) will snap up their assets for peanuts and assimilate their best locations while dumping the rest.

Either way, I agree, it’s interesting. 🌧

**Comment by nelsonic** [comment]
Bloomberg just published this: https://youtu.be/X2LwIiKhczo

**Comment by nelsonic** [comment]
https://www.bloomberg.com/news/articles/2023-08-08/wework-raises-substantial-doubt-about-staying-in-business#xj4y7vzkg

https://www.google.com/search?q=wework+share+price
![image](https://github.com/dwyl/product-roadmap/assets/194400/d7537aea-ce94-409f-bb6b-3af0f9fe6297)

A **`97.86%`** decline means for every **`$10`** "invested" (speculated) in WeWork at IPO is now worth **`$0.21`**. 📉 
Whoever rode that rollercoaster is firing their "investment" manager ... 🔥 
I'm not the kind of person to place bets on the misfortune of others, 👎 
but if I was, a "short sell" on these shares would have made me an absolute fortune! 💰 

Meanwhile Neumann _still_ gets away with it. 🤦‍♂️
